import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-error-container": "#ffdad6",
        "tertiary-container": "#00885d",
        "on-tertiary-fixed": "#002113",
        "surface-dim": "#0b1326",
        "secondary-container": "#0566d9",
        "on-secondary-fixed-variant": "#004395",
        "on-primary-fixed": "#07006c",
        "on-tertiary-container": "#000703",
        "on-secondary-fixed": "#001a42",
        "error-container": "#93000a",
        "on-tertiary": "#003824",
        "on-secondary": "#002e6a",
        "secondary-fixed": "#d8e2ff",
        outline: "#908fa0",
        "primary-fixed-dim": "#c0c1ff",
        "on-surface-variant": "#c7c4d7",
        "surface-container": "#171f33",
        surface: "#0b1326",
        "on-primary-container": "#0d0096",
        "on-secondary-container": "#e6ecff",
        "surface-variant": "#2d3449",
        "surface-bright": "#31394d",
        error: "#ffb4ab",
        "inverse-on-surface": "#283044",
        "primary-fixed": "#e1e0ff",
        "on-primary-fixed-variant": "#2f2ebe",
        "inverse-surface": "#dae2fd",
        "tertiary-fixed": "#6ffbbe",
        primary: "#c0c1ff",
        "on-surface": "#dae2fd",
        "tertiary-fixed-dim": "#4edea3",
        "surface-container-low": "#131b2e",
        "on-primary": "#1000a9",
        "outline-variant": "#464554",
        "surface-container-highest": "#2d3449",
        "secondary-fixed-dim": "#adc6ff",
        "primary-container": "#8083ff",
        "surface-container-lowest": "#060e20",
        tertiary: "#4edea3",
        secondary: "#adc6ff",
        "surface-container-high": "#222a3d",
        "inverse-primary": "#494bd6",
        "on-tertiary-fixed-variant": "#005236",
        "surface-tint": "#c0c1ff",
        "on-background": "#dae2fd",
        "on-error": "#690005",
        background: "#0b1326",
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
        display: ["Geist", "system-ui", "sans-serif"],
        mono: ["Geist", "monospace"],
      },
      fontSize: {
        "body-md": ["14px", { lineHeight: "20px", letterSpacing: "0em", fontWeight: "400" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["16px", { lineHeight: "26px", letterSpacing: "0em", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "mono-sm": ["12px", { lineHeight: "16px", letterSpacing: "0em", fontWeight: "400" }],
        "title-md": ["18px", { lineHeight: "24px", letterSpacing: "0em", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
      },
      spacing: {
        base: "4px",
        lg: "24px",
        xl: "32px",
        md: "16px",
        sm: "8px",
        gutter: "20px",
        xs: "4px",
        "2xl": "48px",
        "margin-desktop": "32px",
        "margin-mobile": "16px",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      animation: {
        "dash": "dash 2s linear forwards",
      },
      keyframes: {
        dash: {
          to: { strokeDashoffset: "0" },
        },
      },
    },
  },
  plugins: [],
};

export default config;
