import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "#13131b",
        "inverse-surface": "#e4e1ed",
        "tertiary-container": "#a078ff",
        "on-secondary-fixed-variant": "#004395",
        "secondary-fixed": "#d8e2ff",
        "inverse-primary": "#494bd6",
        "surface-container-lowest": "#0d0d15",
        "surface-container-low": "#1b1b23",
        primary: "#c0c1ff",
        "secondary-fixed-dim": "#adc6ff",
        "on-surface-variant": "#c7c4d7",
        error: "#ffb4ab",
        "primary-fixed-dim": "#c0c1ff",
        "on-error": "#690005",
        tertiary: "#d0bcff",
        outline: "#908fa0",
        "on-background": "#e4e1ed",
        "on-secondary": "#002e6a",
        "inverse-on-surface": "#303038",
        "on-primary-fixed": "#07006c",
        "on-primary-fixed-variant": "#2f2ebe",
        "on-surface": "#e4e1ed",
        "on-secondary-container": "#e6ecff",
        "secondary-container": "#0566d9",
        "on-tertiary-fixed": "#23005c",
        "outline-variant": "#464554",
        "tertiary-fixed": "#e9ddff",
        "error-container": "#93000a",
        "on-primary-container": "#0d0096",
        "surface-container-high": "#292932",
        "on-primary": "#1000a9",
        "surface-dim": "#13131b",
        "surface-variant": "#34343d",
        "surface-bright": "#393841",
        "surface-container-highest": "#34343d",
        "surface-container": "#1f1f27",
        "on-tertiary-container": "#340080",
        "on-secondary-fixed": "#001a42",
        "primary-container": "#8083ff",
        "on-tertiary": "#3c0091",
        "on-tertiary-fixed-variant": "#5516be",
        "surface-tint": "#c0c1ff",
        "primary-fixed": "#e1e0ff",
        "tertiary-fixed-dim": "#d0bcff",
        surface: "#13131b",
        "on-error-container": "#ffdad6",
        secondary: "#adc6ff",
      },
      fontFamily: {
        sans: ["Geist", "system-ui", "sans-serif"],
        "mono-sm": ["JetBrains Mono", "monospace"],
        "label-sm": ["Geist", "sans-serif"],
        "headline-md": ["Geist", "sans-serif"],
        "headline-lg": ["Geist", "sans-serif"],
        "body-lg": ["Geist", "sans-serif"],
        "headline-lg-mobile": ["Geist", "sans-serif"],
        "body-md": ["Geist", "sans-serif"],
        "display-lg": ["Geist", "sans-serif"],
      },
      fontSize: {
        "mono-sm": ["12px", { lineHeight: "16px", letterSpacing: "0em", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.03em", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", letterSpacing: "0em", fontWeight: "400" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "20px", letterSpacing: "0em", fontWeight: "400" }],
        "display-lg": ["48px", { lineHeight: "52px", letterSpacing: "-0.04em", fontWeight: "700" }],
      },
      spacing: {
        base: "4px",
        xs: "4px",
        sm: "8px",
        md: "16px",
        lg: "24px",
        xl: "32px",
        "2xl": "48px",
        gutter: "24px",
        "margin-mobile": "16px",
        "margin-desktop": "40px",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      animation: {
        blob: "blob 10s infinite",
      },
      keyframes: {
        blob: {
          "0%": { transform: "translate(0px, 0px) scale(1)" },
          "33%": { transform: "translate(30px, -50px) scale(1.1)" },
          "66%": { transform: "translate(-20px, 20px) scale(0.9)" },
          "100%": { transform: "translate(0px, 0px) scale(1)" },
        },
      },
    },
  },
  plugins: [],
};

export default config;
