from .templates import (
    DATA_ANALYSIS_SYSTEM,
    DATA_ANALYSIS_USER_TEMPLATE,
    GENERAL_INSIGHT_SYSTEM,
    GENERAL_INSIGHT_USER_TEMPLATE,
)

__all__ = [
    "DATA_ANALYSIS_SYSTEM",
    "DATA_ANALYSIS_USER_TEMPLATE",
    "GENERAL_INSIGHT_SYSTEM",
    "GENERAL_INSIGHT_USER_TEMPLATE",
]
